import type { ClassId } from "./constants";

// Real CBSE / NCERT chapter lists per class and subject (current rationalised
// syllabus). Combined subjects (Social Science, and the Class 12 humanities)
// prefix each entry with its discipline/book so the dropdown stays readable.
// Subjects with highly variable course options (e.g. Hindi) ship a short
// starter list — the UI always offers an "Other / my own topic" escape hatch.

export const CHAPTERS: Record<ClassId, Record<string, string[]>> = {
  "10": {
    science: [
      "Chemical Reactions and Equations",
      "Acids, Bases and Salts",
      "Metals and Non-metals",
      "Carbon and its Compounds",
      "Life Processes",
      "Control and Coordination",
      "How do Organisms Reproduce?",
      "Heredity",
      "Light – Reflection and Refraction",
      "The Human Eye and the Colourful World",
      "Electricity",
      "Magnetic Effects of Electric Current",
      "Our Environment"
    ],
    mathematics: [
      "Real Numbers",
      "Polynomials",
      "Pair of Linear Equations in Two Variables",
      "Quadratic Equations",
      "Arithmetic Progressions",
      "Triangles",
      "Coordinate Geometry",
      "Introduction to Trigonometry",
      "Some Applications of Trigonometry",
      "Circles",
      "Areas Related to Circles",
      "Surface Areas and Volumes",
      "Statistics",
      "Probability"
    ],
    "social-science": [
      "History: The Rise of Nationalism in Europe",
      "History: Nationalism in India",
      "History: The Making of a Global World",
      "History: The Age of Industrialisation",
      "History: Print Culture and the Modern World",
      "Geography: Resources and Development",
      "Geography: Forest and Wildlife Resources",
      "Geography: Water Resources",
      "Geography: Agriculture",
      "Geography: Minerals and Energy Resources",
      "Geography: Manufacturing Industries",
      "Geography: Lifelines of National Economy",
      "Civics: Power-sharing",
      "Civics: Federalism",
      "Civics: Gender, Religion and Caste",
      "Civics: Political Parties",
      "Civics: Outcomes of Democracy",
      "Economics: Development",
      "Economics: Sectors of the Indian Economy",
      "Economics: Money and Credit",
      "Economics: Globalisation and the Indian Economy",
      "Economics: Consumer Rights"
    ],
    english: [
      "First Flight: A Letter to God",
      "First Flight: Nelson Mandela – Long Walk to Freedom",
      "First Flight: From the Diary of Anne Frank",
      "First Flight: Glimpses of India",
      "First Flight: Madam Rides the Bus",
      "First Flight: The Sermon at Benares",
      "First Flight: The Proposal",
      "Footprints: A Triumph of Surgery",
      "Footprints: The Thief's Story",
      "Footprints: Footprints without Feet",
      "Footprints: The Making of a Scientist",
      "Footprints: The Necklace",
      "Footprints: Bholi"
    ],
    hindi: [
      "क्षितिज (गद्य): नेताजी का चश्मा",
      "क्षितिज (गद्य): बालगोबिन भगत",
      "क्षितिज (काव्य): सूरदास के पद",
      "क्षितिज (काव्य): राम-लक्ष्मण-परशुराम संवाद",
      "स्पर्श (गद्य): अब कैसे छूटे राम नाम",
      "संचयन: हरिहर काका"
    ],
    "information-technology": [
      "Communication Skills",
      "Self-Management Skills",
      "ICT Skills",
      "Entrepreneurial Skills",
      "Green Skills",
      "Digital Documentation (Word Processing)",
      "Electronic Spreadsheet",
      "Database Management System",
      "Web Applications and Security"
    ]
  },
  "12": {
    physics: [
      "Electric Charges and Fields",
      "Electrostatic Potential and Capacitance",
      "Current Electricity",
      "Moving Charges and Magnetism",
      "Magnetism and Matter",
      "Electromagnetic Induction",
      "Alternating Current",
      "Electromagnetic Waves",
      "Ray Optics and Optical Instruments",
      "Wave Optics",
      "Dual Nature of Radiation and Matter",
      "Atoms",
      "Nuclei",
      "Semiconductor Electronics"
    ],
    chemistry: [
      "Solutions",
      "Electrochemistry",
      "Chemical Kinetics",
      "The d- and f-Block Elements",
      "Coordination Compounds",
      "Haloalkanes and Haloarenes",
      "Alcohols, Phenols and Ethers",
      "Aldehydes, Ketones and Carboxylic Acids",
      "Amines",
      "Biomolecules"
    ],
    mathematics: [
      "Relations and Functions",
      "Inverse Trigonometric Functions",
      "Matrices",
      "Determinants",
      "Continuity and Differentiability",
      "Application of Derivatives",
      "Integrals",
      "Application of Integrals",
      "Differential Equations",
      "Vector Algebra",
      "Three Dimensional Geometry",
      "Linear Programming",
      "Probability"
    ],
    biology: [
      "Sexual Reproduction in Flowering Plants",
      "Human Reproduction",
      "Reproductive Health",
      "Principles of Inheritance and Variation",
      "Molecular Basis of Inheritance",
      "Evolution",
      "Human Health and Disease",
      "Microbes in Human Welfare",
      "Biotechnology: Principles and Processes",
      "Biotechnology and its Applications",
      "Organisms and Populations",
      "Ecosystem",
      "Biodiversity and its Conservation"
    ],
    "computer-science": [
      "Python Revision Tour",
      "Functions in Python",
      "File Handling in Python",
      "Data Structures: Stacks",
      "Exception Handling",
      "Database Concepts",
      "Structured Query Language (SQL)",
      "Interface Python with MySQL",
      "Computer Networks"
    ],
    english: [
      "Flamingo (Prose): The Last Lesson",
      "Flamingo (Prose): Lost Spring",
      "Flamingo (Prose): Deep Water",
      "Flamingo (Prose): The Rattrap",
      "Flamingo (Prose): Indigo",
      "Flamingo (Poetry): My Mother at Sixty-six",
      "Flamingo (Poetry): Keeping Quiet",
      "Vistas: The Third Level",
      "Vistas: The Tiger King",
      "Vistas: The Enemy",
      "Vistas: On the Face of It"
    ],
    accountancy: [
      "Accounting for Partnership: Fundamentals",
      "Goodwill: Nature and Valuation",
      "Change in Profit-Sharing Ratio",
      "Admission of a Partner",
      "Retirement and Death of a Partner",
      "Dissolution of Partnership Firm",
      "Accounting for Share Capital",
      "Issue and Redemption of Debentures",
      "Financial Statements of a Company",
      "Analysis of Financial Statements",
      "Accounting Ratios",
      "Cash Flow Statement"
    ],
    "business-studies": [
      "Nature and Significance of Management",
      "Principles of Management",
      "Business Environment",
      "Planning",
      "Organising",
      "Staffing",
      "Directing",
      "Controlling",
      "Financial Management",
      "Financial Markets",
      "Marketing Management",
      "Consumer Protection"
    ],
    economics: [
      "Macro: Introduction to Macroeconomics",
      "Macro: National Income Accounting",
      "Macro: Money and Banking",
      "Macro: Determination of Income and Employment",
      "Macro: Government Budget and the Economy",
      "Macro: Open Economy Macroeconomics",
      "Indian Economy: On the Eve of Independence",
      "Indian Economy: 1950–1990",
      "Indian Economy: Liberalisation, Privatisation and Globalisation",
      "Indian Economy: Poverty",
      "Indian Economy: Human Capital Formation",
      "Indian Economy: Rural Development",
      "Indian Economy: Employment",
      "Indian Economy: Infrastructure",
      "Indian Economy: Environment and Sustainable Development"
    ],
    history: [
      "Bricks, Beads and Bones (The Harappan Civilisation)",
      "Kings, Farmers and Towns",
      "Kinship, Caste and Class",
      "Thinkers, Beliefs and Buildings",
      "Through the Eyes of Travellers",
      "Bhakti-Sufi Traditions",
      "An Imperial Capital: Vijayanagara",
      "Peasants, Zamindars and the State",
      "Kings and Chronicles (The Mughal Courts)",
      "Colonialism and the Countryside",
      "Rebels and the Raj (1857 Revolt)",
      "Colonial Cities",
      "Mahatma Gandhi and the Nationalist Movement",
      "Understanding Partition",
      "Framing the Constitution"
    ],
    "political-science": [
      "The Cold War Era",
      "The End of Bipolarity",
      "US Hegemony in World Politics",
      "Alternative Centres of Power",
      "Contemporary South Asia",
      "International Organisations",
      "Security in the Contemporary World",
      "Environment and Natural Resources",
      "Globalisation",
      "Challenges of Nation-Building",
      "Era of One-Party Dominance",
      "Politics of Planned Development",
      "India's External Relations",
      "The Crisis of Democratic Order",
      "Regional Aspirations"
    ],
    geography: [
      "Human Geography: Nature and Scope",
      "The World Population: Distribution, Density and Growth",
      "Human Development",
      "Primary Activities",
      "Secondary Activities",
      "Tertiary and Quaternary Activities",
      "Transport and Communication",
      "International Trade",
      "India: Population – Distribution, Density, Growth",
      "India: Land Resources and Agriculture",
      "India: Water Resources",
      "India: Mineral and Energy Resources",
      "India: Manufacturing Industries",
      "India: Planning and Sustainable Development"
    ]
  }
};

export function chaptersFor(klass: ClassId, subject: string): string[] {
  return CHAPTERS[klass]?.[subject] ?? [];
}
